openapi: 3.0.1
info:
  title: FERElight
  description: API for the lightweight feature extraction and retrieval engine (FERElight).
  version: 1.1.0
components:
  schemas:
    multimediaobject:
      type: object
      properties:
        objectid:
          type: string
          description: The unique identifier of the object.
        mediatype:
          type: integer
          description: The mediatype enum value of the object.
        name:
          type: string
          description: The name of the object.
        path:
          type: string
          description: The path of the object.
    multimediasegment:
      type: object
      properties:
        segmentid:
          type: string
          description: The unique identifier of the segment.
        objectid:
          type: string
          description: The unique identifier of the object.
        segmentnumber:
          type: integer
          description: The segment number.
        segmentstart:
          type: integer
          description: The start frame of the segment.
        segmentend:
          type: integer
          description: The end frame of the segment.
        segmentstartabs:
          type: number
          description: The double value of the start time in seconds of the segment.
        segmentendabs:
          type: number
          description: The double value of the end time in seconds of the segment.
    scoredsegment:
      type: object
      properties:
        segmentid:
          type: string
          description: The unique identifier of the segment.
        score:
          type: number
          description: The similarity score of the segment.
paths:
  /objectinfo/{database}/{objectid}:
    get:
      summary: Get the information of an object.
      parameters:
        - name: database
          in: path
          required: true
          description: The name of the database to query for the object.
          schema:
            type: string
        - name: objectid
          in: path
          required: true
          description: The unique identifier of the object.
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/multimediaobject"
  /segmentinfo/{database}/{segmentid}:
    get:
      summary: Get the information of a segment.
      parameters:
        - name: database
          in: path
          required: true
          description: The name of the database to query for the segment.
          schema:
            type: string
        - name: segmentid
          in: path
          required: true
          description: The unique identifier of the segment.
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/multimediasegment"
  /objectsegments/{database}/{objectid}:
    get:
      summary: Get the segments of an object.
      parameters:
        - name: database
          in: path
          required: true
          description: The name of the database to query for the object.
          schema:
            type: string
        - name: objectid
          in: path
          required: true
          description: The unique identifier of the object.
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/multimediasegment"
  /objectinfos:
    post:
      summary: Get the information of multiple objects.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: The name of the database to query for the objects.
                objectids:
                  type: array
                  items:
                    type: string
                  description: The unique identifiers of the objects.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/multimediaobject"
  /segmentinfos:
    post:
      summary: Get the information of multiple segments.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: The name of the database to query for the segments.
                segmentids:
                  type: array
                  items:
                    type: string
                  description: The unique identifiers of the segments.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/multimediasegment"
  # Query endpoint with similarity text, OCR and ASR text as input and list of segment ID and similarity score pairs as output
  /query:
    post:
      summary: Query the FERElight engine.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: The name of the database to query.
                similaritytext:
                  type: string
                  description: The similarity text.
                ocrtext:
                  type: string
                  description: The OCR text.
                asrtext:
                  type: string
                  description: The ASR text.
                mergetype:
                  type: string
                  description: Merge Type for the similaritytext
                limit:
                  type: integer
                  description: The maximum number of results to return.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/scoredsegment"
  /querybyexample:
    post:
      summary: Get the nearest neighbors of a segment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: The name of the database to query.
                segmentid:
                  type: string
                  description: The segment ID to find neighbors for.
                limit:
                  type: integer
                  description: The maximum number of results to return.
                  default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/scoredsegment'
  /segmentbytime:
    post:
      summary: Get the segment ID for a given timestamp and object.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: The name of the database to query.
                objectid:
                  type: string
                  description: The object ID to find the segment in.
                timestamp:
                  type: number
                  description: The timestamp to match against.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  segmentid:
                    type: string
                    description: Matching segment ID.

